spring:
  application:
    name: chatapp
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_app
    username: user
    password: P@ssw0rd
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: password
  bucket: chat-app-bucket
  region: ap-southeast-1
